In [0]:
%tensorflow_version 2.x
import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_hub as hub

TensorFlow 2.x selected.


In [0]:
tf.__version__

'2.0.0'

TensorFlow is already loaded. Please restart the runtime to change versions.


In [0]:
!pip install tensorflow --upgrade

     |████████████████████████████████| 86.3MB 317kB/s 
     |████████████████████████████████| 3.8MB 30.2MB/s 
     |████████████████████████████████| 450kB 41.8MB/s 
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: tensorflow 1.15.0
    Uninstalling tensorflow-1.15.0:
      Successfully uninstalled tensorflow-1.15.0


In [0]:
# to show all the available datasets in tensorflow_Datasets
tfds.list_builders()

['abstract_reasoning',
 'aflw2k3d',
 'amazon_us_reviews',
 'bair_robot_pushing_small',
 'bigearthnet',
 'binarized_mnist',
 'binary_alpha_digits',
 'caltech101',
 'caltech_birds2010',
 'caltech_birds2011',
 'cats_vs_dogs',
 'celeb_a',
 'celeb_a_hq',
 'chexpert',
 'cifar10',
 'cifar100',
 'cifar10_corrupted',
 'clevr',
 'cnn_dailymail',
 'coco',
 'coco2014',
 'coil100',
 'colorectal_histology',
 'colorectal_histology_large',
 'curated_breast_imaging_ddsm',
 'cycle_gan',
 'deep_weeds',
 'definite_pronoun_resolution',
 'diabetic_retinopathy_detection',
 'downsampled_imagenet',
 'dsprites',
 'dtd',
 'dummy_dataset_shared_generator',
 'dummy_mnist',
 'emnist',
 'eurosat',
 'fashion_mnist',
 'flores',
 'food101',
 'gap',
 'glue',
 'groove',
 'higgs',
 'horses_or_humans',
 'image_label_folder',
 'imagenet2012',
 'imagenet2012_corrupted',
 'imdb_reviews',
 'iris',
 'kitti',
 'kmnist',
 'lfw',
 'lm1b',
 'lsun',
 'mnist',
 'mnist_corrupted',
 'moving_mnist',
 'multi_nli',
 'nsynth',
 'omniglot',

In [0]:
(train_data, validation_data), test_data = tfds.load(name='imdb_reviews',
         split = (tfds.Split.TRAIN.subsplit([6,4]), tfds.Split.TEST),
         as_supervised=True)

In [8]:
type(train_data)

tensorflow.python.data.ops.dataset_ops._OptionsDataset

In [0]:
# above type doesn't suppoet indexing but batch that will be described below
train_examples_batch, train_lables_batch = next(iter(train_data.batch(10)))

In [13]:
train_examples_batch

<tf.Tensor: id=578, shape=(10,), dtype=string, numpy=
array([b"As a lifelong fan of Dickens, I have invariably been disappointed by adaptations of his novels.<br /><br />Although his works presented an extremely accurate re-telling of human life at every level in Victorian Britain, throughout them all was a pervasive thread of humour that could be both playful or sarcastic as the narrative dictated. In a way, he was a literary caricaturist and cartoonist. He could be serious and hilarious in the same sentence. He pricked pride, lampooned arrogance, celebrated modesty, and empathised with loneliness and poverty. It may be a clich\xc3\xa9, but he was a people's writer.<br /><br />And it is the comedy that is so often missing from his interpretations. At the time of writing, Oliver Twist is being dramatised in serial form on BBC television. All of the misery and cruelty is their, but non of the humour, irony, and savage lampoonery. The result is just a dark, dismal experience: the story p

In [0]:
pretrained_model = "https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1"
hub_layer = hub.KerasLayer(pretrained_model, input_shape=[], dtype=tf.string, trainable=True)

In [18]:
hub_layer(train_examples_batch[:2])

<tf.Tensor: id=759, shape=(2, 20), dtype=float32, numpy=
array([[ 3.9819887 , -4.4838037 ,  5.177359  , -2.3643482 , -3.2938678 ,
        -3.5364532 , -2.4786978 ,  2.5525482 ,  6.688532  , -2.3076782 ,
        -1.9807833 ,  1.1315885 , -3.0339816 , -0.7604128 , -5.743445  ,
         3.4242578 ,  4.790099  , -4.03061   , -5.992149  , -1.7297493 ],
       [ 3.4232912 , -4.230874  ,  4.1488533 , -0.29553518, -6.802391  ,
        -2.5163853 , -4.4002395 ,  1.905792  ,  4.7512794 , -0.40538004,
        -4.3401685 ,  1.0361497 ,  0.9744097 ,  0.71507156, -6.2657013 ,
         0.16533905,  4.560262  , -1.3106939 , -3.1121316 , -2.1338716 ]],
      dtype=float32)>

In [19]:
train_examples_batch[:2]

<tf.Tensor: id=763, shape=(2,), dtype=string, numpy=
array([b"As a lifelong fan of Dickens, I have invariably been disappointed by adaptations of his novels.<br /><br />Although his works presented an extremely accurate re-telling of human life at every level in Victorian Britain, throughout them all was a pervasive thread of humour that could be both playful or sarcastic as the narrative dictated. In a way, he was a literary caricaturist and cartoonist. He could be serious and hilarious in the same sentence. He pricked pride, lampooned arrogance, celebrated modesty, and empathised with loneliness and poverty. It may be a clich\xc3\xa9, but he was a people's writer.<br /><br />And it is the comedy that is so often missing from his interpretations. At the time of writing, Oliver Twist is being dramatised in serial form on BBC television. All of the misery and cruelty is their, but non of the humour, irony, and savage lampoonery. The result is just a dark, dismal experience: the story pe

In [20]:
model = tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16,activation="relu"))
model.add(tf.keras.layers.Dense(1,activation="sigmoid"))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
keras_layer (KerasLayer)     (None, 20)                400020    
_________________________________________________________________
dense (Dense)                (None, 16)                336       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 17        
Total params: 400,373
Trainable params: 400,373
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(optimizer='adam',
             loss='binary_crossentropy',
             metrics=['accuracy'])

In [22]:
model.fit(train_data.shuffle(10000).batch(512),
         epochs=20,
         validation_data = validation_data.batch(512),
         verbose=1)

Epoch 1/20
30/30 [==============================] - 8s 266ms/step - loss: 1.9936 - accuracy: 0.4985 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 2/20
30/30 [==============================] - 7s 220ms/step - loss: 0.8923 - accuracy: 0.5179 - val_loss: 0.7220 - val_accuracy: 0.5608
Epoch 3/20
30/30 [==============================] - 7s 226ms/step - loss: 0.6670 - accuracy: 0.6169 - val_loss: 0.6242 - val_accuracy: 0.6580
Epoch 4/20
30/30 [==============================] - 7s 223ms/step - loss: 0.5983 - accuracy: 0.6911 - val_loss: 0.5835 - val_accuracy: 0.7067
Epoch 5/20
30/30 [==============================] - 7s 224ms/step - loss: 0.5606 - accuracy: 0.7232 - val_loss: 0.5553 - val_accuracy: 0.7279
Epoch 6/20
30/30 [==============================] - 7s 225ms/step - loss: 0.5307 - accuracy: 0.7474 - val_loss: 0.5278 - val_accuracy: 0.7506
Epoch 7/20
30/30 [==============================] - 7s 225ms/step - loss: 0.4995 - accuracy: 0.7731 - val_loss: 0.4979 - val_accuracy: 0.770

In [23]:
model.predict(['Interstellar is the best movie I have ever seen in my life'])

array([[0.93549126]], dtype=float32)

In [24]:
model.predict(['How come one make such a crap movie like bollywood movies'])

array([[0.17206877]], dtype=float32)

In [25]:
# we can give multiple arrays 
model.predict(['Interstellar is the best movie I have ever seen in my life',
              'How come one make such a crap movie like bollywood movies',
              'No story just a waste of time'])

array([[0.93549126],
       [0.17206876],
       [0.06449991]], dtype=float32)